-- Database: LANCHONETEDB

-- DROP DATABASE IF EXISTS "LANCHONETEDB";

CREATE DATABASE "LANCHONETEDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = 10
    IS_TEMPLATE = False;